name: kopa

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.4.4
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  firebase_storage: ^10.3.11
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_svg: ^1.1.4
  fluttertoast: ^8.0.9
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/launcher_icon/launcher_icon.png'

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/vector/
    - assets/1x/
    - assets/2x/
    - assets/3x/
    - assets/launcher_icon/
    - assets/json/
